name: aetheris
description: "A new Flutter project for weather information."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  dio: ^5.6.0
  geolocator: ^13.0.1
  equatable: ^2.0.5
  go_router: ^14.2.3
  get_it: ^7.7.0
  fpdart: ^1.1.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/

  fonts:
     - family: TenorSans
       fonts:
         - asset: fonts/TenorSans-Regular.ttf
     - family: Inter
       fonts:
         - asset: fonts/Inter-Regular.ttf

